# Welcome to Jekyll!
#

# Site settings
title: SUJI
description: |
  Open Source Web POS System
owner: SUJI # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: ledgku@naver.com
baseurl: "/suji" # the subpath of your site, e.g. /blog
url: "http://naver-d2-suji.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/njir123
  github: https://github.com/naver-d2-suji/suji
  linkedin-square: https://linkedin.com/in/hyungtak
  facebook-official: https://facebook.com/ledgku
  email: ledgku@naver.com
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
